### ISSUE TITLE
Feature request: save session in hard disk as a backup

### ISSUE THREAD

**Issue by annymosse** [ekzhang/rustpad#13] opened 2021-06-14 09:57 UTC
since all the sessions are live in RAM and they're expire after 24 hour or end of it, there's some problems when exit that session  accidentally, so i believe save sessions in hard disk as a backup is useful feature at least there's a history of these sessions listed there.

**Comment by ekzhang** [comment] 2021-06-14 23:52
Closing this as a duplicate of #6

**Closed by ekzhang** 2021-06-14 23:52 UTC
